"""empty message

Revision ID: 387b85881c09
Revises: 
Create Date: 2020-05-02 16:31:08.908055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387b85881c09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
